### ISSUE TITLE
报错，这个主题貌似少了东西

### ISSUE THREAD

**Issue by yaozhixing** [lewis-geek/hexo-theme-Aath#66]
我安装好了之后，添加博文结果第二天就报错了，而且很无奈的报错。

**Comment by yaozhixing** [comment]
Error: no mixin named left-container

Backtrace:
        themes/aath/source/css/archive.scss:4
Error: no mixin named left-container

Backtrace:
        themes/aath/source/css/post.scss:5
Error: no mixin named left-container

Backtrace:
        themes/aath/source/css/index.scss:6
Error: no mixin named left-container

Backtrace:
        themes/aath/source/css/tags.scss:3
ERROR Asset render failed: css/archive.css
Error: no mixin named left-container

Backtrace:
        themes/aath/source/css/archive.scss:4
    at Object.module.exports.renderSync (D:\web\yzx\node_modules\_node-sass@4.7.2@node-sass\lib\index.js:439:16)
    at Hexo.<anonymous> (D:\web\yzx\node_modules\_hexo-renderer-sass@0.3.2@hexo-renderer-sass\lib\renderer.js:25:23)
    at D:\web\yzx\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (D:\web\yzx\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\web\yzx\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\web\yzx\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\web\yzx\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\web\yzx\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\web\yzx\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\web\yzx\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\web\yzx\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
ERROR Asset render failed: css/post.css
Error: no mixin named left-container

**Comment by lewis-geek** [comment]
这个报错并不会影响使用，我会在后续版本修掉这个报错，感谢你的反馈！

**Comment by lewis-geek** [comment]
fixed #67
