### ISSUE TITLE
about bugs

### ISSUE THREAD

**Issue by Mryan2005** [lewis-geek/hexo-theme-Aath#93]
我的博客为什么出现了这样的状况
```
 highlight:
    ^
YAMLException: duplicated mapping key at line 80, column -62:
    highlight:
    ^
    at generateError (G:\MyBlog_Mryan\MyBlog\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (G:\MyBlog_Mryan\MyBlog\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at storeMappingPair (G:\MyBlog_Mryan\MyBlog\node_modules\js-yaml\lib\js-yaml\loader.js:308:7)
    at readBlockMapping (G:\MyBlog_Mryan\MyBlog\node_modules\js-yaml\lib\js-yaml\loader.js:1071:9)
    at composeNode (G:\MyBlog_Mryan\MyBlog\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readDocument (G:\MyBlog_Mryan\MyBlog\node_modules\js-yaml\lib\js-yaml\loader.js:1492:3)
    at loadDocuments (G:\MyBlog_Mryan\MyBlog\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at Object.load (G:\MyBlog_Mryan\MyBlog\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at Hexo.yamlHelper (G:\MyBlog_Mryan\MyBlog\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (G:\MyBlog_Mryan\MyBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (G:\MyBlog_Mryan\MyBlog\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.then.text (G:\MyBlog_Mryan\MyBlog\node_modules\hexo\lib\hexo\render.js:61:21)
    at tryCatcher (G:\MyBlog_Mryan\MyBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\MyBlog_Mryan\MyBlog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (G:\MyBlog_Mryan\MyBlog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (G:\MyBlog_Mryan\MyBlog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (G:\MyBlog_Mryan\MyBlog\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (G:\MyBlog_Mryan\MyBlog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (G:\MyBlog_Mryan\MyBlog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (G:\MyBlog_Mryan\MyBlog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (G:\MyBlog_Mryan\MyBlog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
```

**Comment by lewis-geek** [comment]
可能是配置文件里写的值重复了
